POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Mustafa Mustu", 
    "number": "123"
}


###
POST http://localhost:3001/api/persons
content-type: application/json

{
}


###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Mustafa Mustu"
}


###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123"
}